CoreProje/CoreProje/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoreProje.Models;
using Microsoft.AspNetCore.Http;

namespace CoreProje.Controllers
{
    public class AdminsController : Controller
    {
        public BlogdbContext _context = new BlogdbContext();

        // GET: Admins
        public async Task<IActionResult> Index()
        {
            return View(await _context.Admins.ToListAsync());
        }

        // GET: Admins/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var admin = await _context.Admins
                .FirstOrDefaultAsync(m => m.AdminId == id);
            if (admin == null)
            {
                return NotFound();
            }

            return View(admin);
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public  IActionResult Login(string Email, string Password)
        {
            var login =  _context.Admins.Where(x => x.Email == Email && x.Password==Password).FirstOrDefault();
            if (login != null)/*login.Email == Email && login.Password == Password*/
            {
                if(login.Yetki==null)
                    login.Yetki = "pasif";
                //HttpContext.Session["AdminId"] = login.AdminId;
                HttpContext.Session.SetInt32("AdminId", login.AdminId);
                HttpContext.Session.SetString("Email", login.Email);
                HttpContext.Session.SetString("Yetki", login.Yetki);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Uyari = "Kullanıcı Adı veya Şifre Hatalı... Tekrar Deneyin...";
            }
            return View();
        }
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SignUp([Bind("Email,Password,AdminId")] Admin model)
        {
            if (ModelState.IsValid)
            {
                await _context.AddAsync(model);
                
                await _context.SaveChangesAsync();

                return RedirectToAction("Login");

            }
            return View(model);
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return Redirect("Index");
        }

        // GET: Admins/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AdminId,Email,Password,Yetki")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                _context.Add(admin);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(admin);
        }

        // GET: Admins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var admin = await _context.Admins.FindAsync(id);
            if (admin == null)
            {
                return NotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AdminId,Email,Password,Yetki")] Admin admin)
        {
            if (id != admin.AdminId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(admin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdminExists(admin.AdminId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(admin);
        }

        // GET: Admins/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var admin = await _context.Admins
                .FirstOrDefaultAsync(m => m.AdminId == id);
            if (admin == null)
            {
                return NotFound();
            }

            return View(admin);
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var admin = await _context.Admins.FindAsync(id);
            _context.Admins.Remove(admin);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdminExists(int id)
        {
            return _context.Admins.Any(e => e.AdminId == id);
        }
    }
}

CoreProje/CoreProje/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoreProje.Models;

namespace CoreProje.Controllers
{
    public class BlogsController : Controller
    {

        public BlogdbContext _context = new BlogdbContext();

        // GET: Blogs
        public async Task<IActionResult> Index()
        {
            var blogdbContext = _context.Blogs.Include(b => b.Admin).Include(b => b.Kategori);
            return View(await blogdbContext.ToListAsync());
        }

        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.Admin)
                .Include(b => b.Kategori)
                .FirstOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        public IActionResult Create()
        {
            ViewData["AdminId"] = new SelectList(_context.Admins, "AdminId", "AdminId");
            ViewData["KategoriId"] = new SelectList(_context.Kategoris, "KategoriId", "KategoriId");
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlogId,KategoriId,Baslik,AdminId,Icerik,Resim")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AdminId"] = new SelectList(_context.Admins, "AdminId", "AdminId", blog.AdminId);
            ViewData["KategoriId"] = new SelectList(_context.Kategoris, "KategoriId", "KategoriId", blog.KategoriId);
            return View(blog);
        }

        // GET: Blogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            ViewData["AdminId"] = new SelectList(_context.Admins, "AdminId", "AdminId", blog.AdminId);
            ViewData["KategoriId"] = new SelectList(_context.Kategoris, "KategoriId", "KategoriId", blog.KategoriId);
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BlogId,KategoriId,Baslik,AdminId,Icerik")] Blog blog)
        {
            if (id != blog.BlogId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.BlogId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AdminId"] = new SelectList(_context.Admins, "AdminId", "AdminId", blog.AdminId);
            ViewData["KategoriId"] = new SelectList(_context.Kategoris, "KategoriId", "KategoriId", blog.KategoriId);
            return View(blog);
        }

        // GET: Blogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.Admin)
                .Include(b => b.Kategori)
                .FirstOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.Blogs.FindAsync(id);
            _context.Blogs.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return _context.Blogs.Any(e => e.BlogId == id);
        }
    }
}

CoreProje/CoreProje/Controllers/YorumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoreProje.Models;

namespace CoreProje.Controllers
{
    public class YorumsController : Controller
    {
        public BlogdbContext _context = new BlogdbContext();

        // GET: Yorums
        public async Task<IActionResult> Index()
        {
            var blogdbContext = _context.Yorums.Include(y => y.Admin).Include(y => y.Blog);
            return View(await blogdbContext.ToListAsync());
        }

        // GET: Yorums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var yorum = await _context.Yorums
                .Include(y => y.Admin)
                .Include(y => y.Blog)
                .FirstOrDefaultAsync(m => m.YorumId == id);
            if (yorum == null)
            {
                return NotFound();
            }

            return View(yorum);
        }

        // GET: Yorums/Create
        public IActionResult Create()
        {
            ViewData["AdminId"] = new SelectList(_context.Admins, "AdminId", "AdminId");
            ViewData["BlogId"] = new SelectList(_context.Blogs, "BlogId", "BlogId");
            return View();
        }

        // POST: Yorums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("YorumId,Yicerik,Tarih,AdminId,BlogId")] Yorum yorum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(yorum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AdminId"] = new SelectList(_context.Admins, "AdminId", "AdminId", yorum.AdminId);
            ViewData["BlogId"] = new SelectList(_context.Blogs, "BlogId", "BlogId", yorum.BlogId);
            return View(yorum);
        }

        // GET: Yorums/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var yorum = await _context.Yorums.FindAsync(id);
            if (yorum == null)
            {
                return NotFound();
            }
            ViewData["AdminId"] = new SelectList(_context.Admins, "AdminId", "AdminId", yorum.AdminId);
            ViewData["BlogId"] = new SelectList(_context.Blogs, "BlogId", "BlogId", yorum.BlogId);
            return View(yorum);
        }

        // POST: Yorums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("YorumId,Yicerik,Tarih,AdminId,BlogId")] Yorum yorum)
        {
            if (id != yorum.YorumId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(yorum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!YorumExists(yorum.YorumId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AdminId"] = new SelectList(_context.Admins, "AdminId", "AdminId", yorum.AdminId);
            ViewData["BlogId"] = new SelectList(_context.Blogs, "BlogId", "BlogId", yorum.BlogId);
            return View(yorum);
        }

        // GET: Yorums/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var yorum = await _context.Yorums
                .Include(y => y.Admin)
                .Include(y => y.Blog)
                .FirstOrDefaultAsync(m => m.YorumId == id);
            if (yorum == null)
            {
                return NotFound();
            }

            return View(yorum);
        }

        // POST: Yorums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var yorum = await _context.Yorums.FindAsync(id);
            _context.Yorums.Remove(yorum);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool YorumExists(int id)
        {
            return _context.Yorums.Any(e => e.YorumId == id);
        }
    }
}

CoreProje/CoreProje/Views/Shared/_Culture.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@inject Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> locOptions

@{ 
    var culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var cultureList = locOptions.Value.SupportedUICultures.Select(x => new SelectListItem { Value = x.Name, Text = localizer.GetString(x.Name) }).ToList();
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<div>
    <form asp-action="CultureManagement" asp-controller="Home" method="post"
          asp-route-returnUrl="@returnUrl">
        
        <select name="culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList"
                onchange="this.form.submit();"></select>
    </form>
</div>

CoreProje/CoreProje/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@using Microsoft.AspNetCore.Http;

@{
    int? AdminId = Context.Session.GetInt32("AdminId");
    string AdminYetki = Context.Session.GetString("Yetki");
    string mail = Context.Session.GetString("Email");
    if (!AdminId.HasValue)   // eğer adminin bilgileri doğruysa siteye girer
    {
        Context.Response.Redirect("/Admins/Login");
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Want to start your travel agency online and need website for your travel business? Start with travel agency responsive website template. Its absolutely free.">
    <meta name="keywords" content="travel, tour, tourism, honeymoon pacakage, summer trip, exotic vacation, destination, international, domestic website template, holiday, travel agecny responsive website template">
    <title>Tour and Travel - Responsive Website Template</title>
    <!-- Bootstrap -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <!-- Style CSS -->
    <link href="~/css/style.css" rel="stylesheet">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <!-- FontAwesome CSS -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/6c7bb4439b.js" crossorigin="anonymous"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <header>
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 hidden-sm col-sm-12">
                        @*<div class="call-info">
                                <p class="call-text">Any Question? Call Us:<strong></strong></p>
                            </div>*@
                    </div>
                    <div class="col-md-8 hidden-sm hidden-xs">
                        <div class="social">
                            <ul>
                                <li><partial name="_Culture" /></li>
                                <li><i class="fas fa-user"></i> <strong> @mail</strong> </li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-wrapper">
            <div class="header">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4 col-md-2 col-sm-12 col-xs-12">
                            <a href="/Home/Index"><img src="/images/logo.png" alt="Tour and Travel Agency - Responsive Website Template"></a>
                        </div>
                        <div class="col-lg-8 col-md-10 col-sm-12 col-xs-12">
                            <div class="navigation">
                                <div id="navigation">
                                    <ul>
                                        <li class="active"><a href="/Home/Index">@localizer["home"]</a></li>
                                        @if (AdminYetki == "aktif") // Adminin yetkisi varsa admin panelini göster
                                        {
                                            <li class="has-sub">
                                                <a asp-area="" asp-controller="Admins" asp-action="Index">Admin</a>
                                                <ul>
                                                    <li><a asp-area="" asp-controller="Home" asp-action="Category">@localizer["category"]</a> </li>
                                                    <li><a asp-area="" asp-controller="Yorums" asp-action="Index">@localizer["comment"]</a> </li>
                                                    <li><a asp-area="" asp-controller="Admins" asp-action="Index">Admin</a></li>
                                                    <li><a asp-area="" asp-controller="Blogs" asp-action="Index">Blog</a> </li>
                                                </ul>
                                            </li>
                                        }
                                        <li class="has-sub">
                                            <a asp-area="" asp-controller="Home" asp-action="Tours">@localizer["bcategory"]</a>
                                            <ul>
                                                <li><a asp-area="" asp-controller="Home" asp-action="YiciTour">@localizer["yici"]</a></li>
                                                <li><a asp-area="" asp-controller="Home" asp-action="YdisiTour">@localizer["ydisi"]</a></li>
                                            </ul>
                                        </li>
                                        <li><a asp-area="" asp-controller="Admins" asp-action="Logout" style="font-family: 'Open Sans', sans-serif;"><i class="fas fa-sign-out-alt"></i>  @localizer["logout"]</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </header>

    @RenderBody()

    <!-- footer start -->
    <div class="footer">
        <div class="container">
            <div class="row">
                <!-- footer-about-start -->
                <div class=" col-lg-3 col-md-3 col-sm-3 col-xs-12">
                    <div class="footer-widget">
                        <h3 class="footer-title ">@localizer["about"]</h3>
                        <p>@localizer["review"]</p>
                        <a href="#" class="footer-link">More about us</a>
                    </div>
                </div>
                <!-- footer-about-close -->
                <!-- footer-location-start -->
                <div class=" col-lg-3 col-md-3 col-sm-3 col-xs-12">
                    <div class="footer-widget">
                        <h3 class="footer-title">@localizer["location"]</h3>
                        <ul class="arrow arrow-chevron-circle-right">
                            <li><a href="#">New York</a></li>
                            <li><a href="#">Amsterdam</a></li>
                            <li><a href="#">Ankara</a></li>
                            <li><a href="#">Nairobi</a></li>
                            <li><a href="#">Tokyo</a></li>
                        </ul>
                    </div>
                </div>
                <!-- footer-location-close -->
                <!-- footer-contact-start -->
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 ">
                    <div class="footer-widget">
                        <h3 class="footer-title">@localizer["contact"]</h3>
                        <div class="contact-info">
                            <ul>
                                <li>@localizer["adres"]</li>
                                <li>252-386-7004 </li>
                                <li>info@yourwebsitedomian.com</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- footer-contact-close -->
                <!-- footer-social-start -->
                <div class="col-lg-3 col-md-3 col-sm-2 col-xs-12 ">
                    <div class="footer-widget">
                        <h3 class="footer-title">@localizer["follow"]</h3>
                        <div class="footer-social">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- footer-social-close -->
            </div>
        </div>
    </div>
    <!-- tiny-footer-start -->
    <div class="tiny-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">Shared by <i class="fa fa-love"></i><a href="https://bootstrapthemes.co">BootstrapThemes</a></div>
            </div>
        </div>
        <!-- tiny-footer-start -->
    </div>
    <!-- footer close -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/js/jquery.min.js" type="text/javascript"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/js/menumaker.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/js/jquery.sticky.js"></script>
    <script type="text/javascript" src="~/js/sticky-header.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>